"""Definición de preguntas del onboarding — 15 obligatorias + 20 opcionales."""

# Secciones: Marca, Audiencia, Contenido, Identidad, Operación

PREGUNTAS = [
    # ── OBLIGATORIAS (15) ──────────────────────────────────────
    {"id": 1, "seccion": "Marca", "obligatoria": True, "tipo": "texto", "pregunta": "¿Cuál es el nombre de tu marca?", "campos": ["nombre_marca"]},
    {
        "id": 2,
        "seccion": "Marca",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Cuál es el rubro o industria de tu negocio?",
        "campos": ["industria"],
    },
    {"id": 3, "seccion": "Marca", "obligatoria": True, "tipo": "texto", "pregunta": "Describí tu negocio en 2-3 líneas.", "campos": ["descripcion"]},
    {
        "id": 4,
        "seccion": "Marca",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Qué problema resuelve tu marca? (propuesta de valor)",
        "campos": ["propuesta_valor"],
    },
    {"id": 5, "seccion": "Marca", "obligatoria": True, "tipo": "texto", "pregunta": "¿En qué ciudad o zona operás?", "campos": ["ciudad_zona"]},
    {
        "id": 6,
        "seccion": "Audiencia",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Quién es tu cliente ideal? (edad, perfil, situación)",
        "campos": ["publico_objetivo"],
    },
    {
        "id": 7,
        "seccion": "Audiencia",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Cuál es el principal dolor o problema de tu cliente ideal?",
        "campos": ["dolor_cliente"],
    },
    {
        "id": 8,
        "seccion": "Marca",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Qué vendés exactamente? (nombre + precio + beneficio clave)",
        "campos": ["productos_servicios"],
    },
    {
        "id": 9,
        "seccion": "Operación",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "CTA principal: ¿a dónde mandás al cliente? (WhatsApp, web, DM, reserva)",
        "campos": ["cta_principal"],
    },
    {
        "id": 10,
        "seccion": "Identidad",
        "obligatoria": True,
        "tipo": "select",
        "pregunta": "¿Cuál es el tono de voz de tu marca?",
        "campos": ["tono_voz"],
        "opciones": ["cercano", "profesional", "humoristico", "inspiracional", "informativo", "urgente"],
    },
    {
        "id": 11,
        "seccion": "Identidad",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Cuáles son los colores de tu marca? (pegá hex codes o describí)",
        "campos": ["colores_marca"],
    },
    {
        "id": 12,
        "seccion": "Identidad",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Hay palabras o frases que tu marca NUNCA debe usar?",
        "campos": ["palabras_prohibidas"],
    },
    {
        "id": 13,
        "seccion": "Operación",
        "obligatoria": True,
        "tipo": "texto",
        "pregunta": "¿Con qué frecuencia querés publicar? (posts por semana)",
        "campos": ["frecuencia_publicacion"],
    },
    {
        "id": 14,
        "seccion": "Operación",
        "obligatoria": True,
        "tipo": "select",
        "pregunta": "¿Aprobás cada post antes de publicar o preferís publicación directa?",
        "campos": ["aprobacion_contenido"],
        "opciones": ["apruebo cada post", "publicacion directa", "depende del contenido"],
    },
    {
        "id": 15,
        "seccion": "Operación",
        "obligatoria": True,
        "tipo": "select",
        "pregunta": "¿En qué redes sociales está activa tu marca?",
        "campos": ["redes_activas"],
        "opciones": ["Instagram", "Facebook", "Instagram y Facebook"],
    },
    # ── OPCIONALES (~20) ───────────────────────────────────────
    {
        "id": 16,
        "seccion": "Marca",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Cuál es tu propuesta de valor diferencial frente a la competencia?",
        "campos": ["diferenciadores"],
    },
    {
        "id": 17,
        "seccion": "Marca",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Cuáles son tus principales competidores? (2-3 nombres)",
        "campos": ["competidores"],
    },
    {
        "id": 18,
        "seccion": "Marca",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Por qué un cliente te elegiría a vos sobre la competencia?",
        "campos": ["ventaja_competitiva"],
    },
    {
        "id": 19,
        "seccion": "Marca",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Tenés testimonios o resultados concretos de clientes?",
        "campos": ["testimonios_resultados"],
    },
    {
        "id": 20,
        "seccion": "Marca",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "3 adjetivos que definen tu marca.",
        "campos": ["adjetivos_marca"],
    },
    {"id": 21, "seccion": "Marca", "obligatoria": False, "tipo": "texto", "pregunta": "¿Cuál es el sitio web de tu marca?", "campos": ["sitio_web"]},
    {
        "id": 22,
        "seccion": "Audiencia",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "Describí tu cliente ideal de forma más detallada (ICP).",
        "campos": ["icp_descripcion"],
    },
    {
        "id": 23,
        "seccion": "Contenido",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Cuál es tu objetivo principal en redes sociales?",
        "campos": ["objetivos_periodo"],
    },
    {
        "id": 24,
        "seccion": "Contenido",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Qué tipo de contenido funciona mejor con tu audiencia?",
        "campos": ["ejemplos_contenido_aprobado"],
    },
    {
        "id": 25,
        "seccion": "Contenido",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Qué contenido NO querés que se publique nunca?",
        "campos": ["politica_respuestas"],
    },
    {
        "id": 26,
        "seccion": "Identidad",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Qué palabras o frases representan tu marca?",
        "campos": ["palabras_clave"],
    },
    {
        "id": 27,
        "seccion": "Identidad",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Tenés tipografía definida para la marca?",
        "campos": ["tipografia"],
    },
    {
        "id": 28,
        "seccion": "Identidad",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "Si tu marca fuera una persona, ¿cómo sería?",
        "campos": ["personalidad_marca"],
    },
    {
        "id": 29,
        "seccion": "Identidad",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Qué marcas admirás o usás como referencia visual?",
        "campos": ["marcas_referencia"],
    },
    {
        "id": 30,
        "seccion": "Identidad",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "Describí la estética visual que te gustaría para tus publicaciones.",
        "campos": ["estetica_visual"],
    },
    {
        "id": 31,
        "seccion": "Operación",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿En qué horarios está más activa tu audiencia?",
        "campos": ["icp_cargo"],
    },
    {
        "id": 32,
        "seccion": "Operación",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Cuál es la temporada alta y baja de tu negocio?",
        "campos": ["temporada_alta_baja"],
    },
    {
        "id": 33,
        "seccion": "Operación",
        "obligatoria": False,
        "tipo": "texto",
        "pregunta": "¿Hay fechas especiales importantes para tu rubro?",
        "campos": ["fechas_especiales"],
    },
    {
        "id": 34,
        "seccion": "Operación",
        "obligatoria": False,
        "tipo": "select",
        "pregunta": "¿Tenés fotos propias de productos, local o equipo?",
        "campos": ["tiene_fotos_propias"],
        "opciones": ["Sí, muchas", "Algunas", "Pocas", "No tengo"],
    },
    {
        "id": 35,
        "seccion": "Operación",
        "obligatoria": False,
        "tipo": "select",
        "pregunta": "¿Preferís imágenes generadas por IA o fotos reales?",
        "campos": ["preferencia_imagenes"],
        "opciones": ["IA", "Fotos reales", "Mezcla de ambas"],
    },
]

PREGUNTAS_OBLIGATORIAS = [p for p in PREGUNTAS if p["obligatoria"]]
