export const BASE_URL = "/api";

export const ENDPOINTS = {
  LOGIN: `${BASE_URL}/auth/login`,
  LOGOUT: `${BASE_URL}/auth/logout`,
  ME: `${BASE_URL}/auth/me`,
  CLIENTES: `${BASE_URL}/clientes`,
  CLIENTE_RENOVAR: (id) => `${BASE_URL}/clientes/${id}/renovar`,
  CLIENTE_ESTADO: (id) => `${BASE_URL}/clientes/${id}/estado`,
  CLIENTE_MARCAS: (id) => `${BASE_URL}/clientes/${id}/marcas`,
  USUARIOS: `${BASE_URL}/usuarios`,
  USUARIO_PERMISOS: (id) => `${BASE_URL}/usuarios/${id}/permisos`,
  FEATURE_FLAGS: `${BASE_URL}/feature-flags`,
  FEATURE_FLAG: (f) => `${BASE_URL}/feature-flags/${f}`,
  CONTACTOS: `${BASE_URL}/contactos`,
  CONTACTOS_BUSCAR: `${BASE_URL}/contactos/buscar`,
  CONTACTOS_GUARDAR: `${BASE_URL}/contactos/guardar`,
  CONTENIDO: `${BASE_URL}/contenido`,
  CONTENIDO_GENERAR: `${BASE_URL}/contenido/generar`,
  CONTENIDO_USAGE: `${BASE_URL}/contenido/usage`,
  CONTENIDO_API_KEY: `${BASE_URL}/contenido/api-key`,
  CONTENIDO_APROBAR: (id) => `${BASE_URL}/contenido/${id}/aprobar`,
  CONTENIDO_RECHAZAR: (id) => `${BASE_URL}/contenido/${id}/rechazar`,
  CONTENIDO_PUBLICAR_DIRECTO: (id) => `${BASE_URL}/contenido/${id}/publicar-directo`,
  TEMPLATES: `${BASE_URL}/contenido/templates`,
  CALENDARIO: `${BASE_URL}/calendario`,
  SOCIAL_CONECTAR: `${BASE_URL}/social/conectar`,
  SOCIAL_CONECTAR_CALLBACK: `${BASE_URL}/social/conectar/callback`,
  SOCIAL_PUBLICAR: `${BASE_URL}/social/publicar`,
  SOCIAL_PROGRAMAR: `${BASE_URL}/social/programar`,
  SOCIAL_CUENTAS: `${BASE_URL}/social/cuentas`,
  SOCIAL_PUBLICACIONES: `${BASE_URL}/social/publicaciones`,
  ADS_CAMPANAS: `${BASE_URL}/ads/campanas`,
  ADS_APROBAR: (id) => `${BASE_URL}/ads/campanas/${id}/aprobar`,
  ADS_PAUSAR: (id) => `${BASE_URL}/ads/campanas/${id}/pausar`,
  ADS_UMBRALES: `${BASE_URL}/ads/umbrales`,
  ADS_VERIFICAR: `${BASE_URL}/ads/verificar-umbrales`,
  SEO_KEYWORDS: `${BASE_URL}/seo/keywords`,
  SEO_INVESTIGAR: `${BASE_URL}/seo/keywords/investigar`,
  SEO_MONITOREAR: `${BASE_URL}/seo/keywords/monitorear`,
  SEO_AUDITORIA: `${BASE_URL}/seo/auditoria`,
  SEO_BRIEFS: `${BASE_URL}/seo/briefs`,
  SEO_CONFIG: `${BASE_URL}/seo/config`,
  SEO_COMPETIDOR: `${BASE_URL}/seo/competidor`,
  ANALYTICS_DASHBOARD: `${BASE_URL}/analytics/dashboard`,
  ANALYTICS_TENDENCIAS: `${BASE_URL}/analytics/tendencias`,
  ANALYTICS_TOP_CONTENIDO: `${BASE_URL}/analytics/top-contenido`,
  ANALYTICS_METRICAS: `${BASE_URL}/analytics/metricas`,
  REPORTING: `${BASE_URL}/reporting`,
  REPORTING_GENERAR: `${BASE_URL}/reporting/generar`,
  REPORTING_DETALLE: (id) => `${BASE_URL}/reporting/${id}`,
  ANALYTICS_CONSOLIDAR: `${BASE_URL}/analytics/consolidar`,
  ANALYTICS_KPIS: `${BASE_URL}/analytics/kpis`,
  ANALYTICS_REPORTES: `${BASE_URL}/analytics/reportes`,
  ANALYTICS_GENERAR_REPORTE: `${BASE_URL}/analytics/reportes/generar`,
  ANALYTICS_ALERTAS: `${BASE_URL}/analytics/alertas`,
  ANALYTICS_CONFIG: `${BASE_URL}/analytics/config`,
  COMUNIDAD_HISTORIAL: `${BASE_URL}/comunidad/historial`,
  COMUNIDAD_MENSAJES: `${BASE_URL}/comunidad/mensajes`,
  COMUNIDAD_PENDIENTES: `${BASE_URL}/comunidad/mensajes/pendientes`,
  COMUNIDAD_RESPONDER: (id) => `${BASE_URL}/comunidad/mensajes/${id}/responder`,
  COMUNIDAD_LEADS: `${BASE_URL}/comunidad/leads`,
  COMUNIDAD_MENCIONES: `${BASE_URL}/comunidad/menciones`,
  COMUNIDAD_URGENTES: `${BASE_URL}/comunidad/menciones/urgentes`,
  COMUNIDAD_MONITOREAR: `${BASE_URL}/comunidad/monitorear`,
  COMUNIDAD_SENTIMIENTO: `${BASE_URL}/comunidad/sentimiento`,
  COMUNIDAD_CONFIG: `${BASE_URL}/comunidad/config`,
  COMUNIDAD_LISTENING: `${BASE_URL}/comunidad/config/listening`,
  AUTOMATIZACIONES: `${BASE_URL}/automatizaciones`,
  AUTOMATIZACION_ACTIVAR: (tipo) => `${BASE_URL}/automatizaciones/${tipo}/activar`,
  AUTOMATIZACION_DESACTIVAR: (tipo) => `${BASE_URL}/automatizaciones/${tipo}/desactivar`,
  AUTOMATIZACION_EJECUTAR: (tipo) => `${BASE_URL}/automatizaciones/${tipo}/ejecutar`,
  AGENTES: `${BASE_URL}/agentes`,
  AGENTE_CONFIG: (nombre) => `${BASE_URL}/agentes/${nombre}`,
  AGENTE_EJECUTAR: (nombre) => `${BASE_URL}/agentes/${nombre}/ejecutar`,
  IMAGENES: `${BASE_URL}/imagenes`,
  IMAGENES_GENERAR: `${BASE_URL}/imagenes/generar`,
  IMAGENES_PARA_CONTENIDO: (id) => `${BASE_URL}/imagenes/generar-para-contenido/${id}`,
  IMAGENES_CARRUSEL: (id) => `${BASE_URL}/imagenes/generar-carrusel/${id}`,
  IMAGENES_ASOCIAR: (imgId, contId) => `${BASE_URL}/imagenes/${imgId}/asociar-contenido/${contId}`,
  IMAGENES_OPENAI_KEY: `${BASE_URL}/imagenes/openai-key`,
  LISTENING_ESCANEAR: `${BASE_URL}/listening/escanear`,
  LISTENING_MENCIONES: `${BASE_URL}/listening/menciones`,
  LISTENING_RESUMEN: `${BASE_URL}/listening/resumen`,
  LISTENING_ALERTAS: `${BASE_URL}/listening/alertas`,
  LISTENING_PROCESAR: (id) => `${BASE_URL}/listening/menciones/${id}/procesar`,
  ESTRATEGIA_COMPETENCIA: `${BASE_URL}/estrategia/analizar-competencia`,
  ESTRATEGIA_PLAN: `${BASE_URL}/estrategia/plan-contenido`,
  ESTRATEGIA_SUGERENCIAS: `${BASE_URL}/estrategia/sugerencias`,
  ESTRATEGIA_IMPLEMENTAR: (id) => `${BASE_URL}/estrategia/sugerencias/${id}/implementada`,
  ONBOARDING_ESTADO: `${BASE_URL}/onboarding/estado`,
  ONBOARDING_INICIAR: `${BASE_URL}/onboarding/iniciar`,
  ONBOARDING_GUARDAR: `${BASE_URL}/onboarding/guardar`,
  ONBOARDING_COMPLETAR: `${BASE_URL}/onboarding/completar`,
  ONBOARDING_SUGERIR: `${BASE_URL}/onboarding/sugerir`,
  ONBOARDING_AUTOCOMPLETAR: `${BASE_URL}/onboarding/autocompletar`,
  ONBOARDING_PASO: (n) => `${BASE_URL}/onboarding/paso/${n}`,
  MARCA_PERFIL: `${BASE_URL}/marca/perfil`,
  ONBOARDING_MEMORIA: `${BASE_URL}/onboarding/memoria`,
  ONBOARDING_AGENTE: (a) => `${BASE_URL}/onboarding/memoria/agente/${a}`,
  ONBOARDING_REGENERAR: `${BASE_URL}/onboarding/memoria/regenerar`,
};
